tv2/sisyfos-audio-controller

src/components/App.js, src/components/Settings.js, src/reducers/channelsReducer.js, src/reducers/settingsReducer.js, src/utils/DEFAULTS.js, src/utils/OSCPRESETS.js, src/utils/OscServer.js, src/utils/SettingsStorage.js, src/utils/productSpecific/behringer.js
Behringer Xr series now works in "master" mode.
As there´s no secondary gain stage to use, the fader on the Behringer is used for fade in/out.
=> Support for Behringer XR-series (without metering)

src/reducers/channelsReducer.js, src/utils/MixerConnection.js, src/utils/OscMixerConnection.js
Only one fade running pr channel
Clears active fade if a new one is ordered.
=> Fade In/Out fixes

.babelrc, src/components/Channel.js, src/components/VuMeter.js, src/reducers/channelsReducer.js, src/utils/OscMixerConnection.js
Each channel only rerenders if changes are made on that specific channel.
=> Speed optimising - Each channel

README.md, package.json, src/components/Settings.js, src/constants/MixerProtocolPresets.js
Settings added pulldown menu for presets
Reformatted "MixerProtocolPresets.js" - so unfortunately all lines are registered as changed.
=> Settings added pulldown menu for presets

README.md, src/constants/MixerProtocolPresets.js, src/utils/OscMixerConnection.js
Ardour master mode support. (www.ardour.org)
fix: check for position of {channel} in different OSC protocols
=> FEAT: Ardour support

src/constants/MixerProtocolPresets.ts, src/constants/mixerProtocols/reaperMaster.ts, src/utils/HuiMidiRemoteConnection.ts, src/utils/MixerConnection.ts
=> Fix: Change of Gain while fading

src/utils/AutomationConnection.ts
OSC server could only receive local connections. IP changed to 0.0.0.0
=> fix: AutomationConnection

README.md, src/components/App.tsx, src/components/Channel.tsx, src/components/Channels.tsx, src/components/GrpFader.tsx, src/index.tsx, src/utils/AutomationConnection.ts, src/utils/HuiMidiRemoteConnection.ts, src/utils/MixerConnection.ts
Added optional second argument in /ch/1/mix/pgmon -I {channel} -f {fadetime}
=> Feature/individual fade time from Automation

package.json, src/@types/emberplus/index.d.ts, src/constants/AutomationPresets.ts, src/constants/MixerProtocolPresets.ts, src/constants/mixerProtocols/EmberLawo.ts, src/constants/mixerProtocols/ardourMaster.ts, src/constants/mixerProtocols/behringerXrMaster.ts, src/constants/mixerProtocols/genericMidi.ts, src/constants/mixerProtocols/midasMaster.ts, src/constants/mixerProtocols/reaper.ts, src/constants/mixerProtocols/reaperMaster.ts, src/utils/AutomationConnection.ts, src/utils/CasparCGConnection.ts, src/utils/EmberMixerConnection.ts, src/utils/MidiMixerConnection.ts, src/utils/MixerConnection.ts, src/utils/OscMixerConnection.ts
Basic implementation for Ember mono channels.
Work will progress when Generic channel structure is updated
=> Feature/emberplus - preliminary support.

README.md, src/constants/MixerProtocolPresets.ts, src/constants/mixerProtocols/DmxIs.ts
=> DMXIS protocol

src/components/Settings.tsx, src/reducers/settingsReducer.ts, src/utils/MixerConnection.ts
Individual fadetime for Voice Over
=> Feat/vo fadetime 

src/assets/css/ChanStrip.css, src/assets/css/Channel.css, src/components/ChanStrip.tsx, src/components/Channel.tsx, src/components/Channels.tsx, src/components/Settings.tsx, src/reducers/settingsReducer.ts
Moving settings for channel in to a channel strip and preparing more advanced channel settings.
(e.g. sends, eq, comp etc.)
For now only includes routing.
=> Feature - Channel Strip

src/constants/MixerProtocolInterface.ts, src/constants/mixerProtocols/DmxIs.ts, src/constants/mixerProtocols/EmberLawo.ts, src/constants/mixerProtocols/SSLsystemT.ts, src/constants/mixerProtocols/StuderVistaEmber.ts, src/constants/mixerProtocols/ardourMaster.ts, src/constants/mixerProtocols/behringerXrMaster.ts, src/constants/mixerProtocols/casparCGMaster.ts, src/constants/mixerProtocols/genericMidi.ts, src/constants/mixerProtocols/midasMaster.ts, src/constants/mixerProtocols/reaperMaster.ts, src/constants/mixerProtocols/yamahaQLCL.ts, src/utils/OscMixerConnection.ts
Rewrite checkOscCommand()
Receive aux level from X32
Rename MONITOR to AUX_LEVEL in protocols
=> Chore/cleanup - OSC protocol

README.md, server/utils/logger.ts, server/utils/mixerConnections/CasparCGConnection.ts
added Winston logger in CasparCGConecction
added Winston logger console level support with: --loggerConsoleLevel='verbose' runtime argument
=> Feat/casparcg v2 - winston logger support

server/constants/mixerProtocols/yamahaQLCL.ts, server/utils/MixerConnection.ts, server/utils/mixerConnections/QlClMixerConnection.ts, server/utils/mixerConnections/YamahaQlClConnection.ts
Improved Yamaha support:
Two way integration, gets realtime fader and mute state from desk
Prepared for adding - meter, eq, dyn, aux when needed.
=> Feat/yamaha QL1

README.md, server/constants/MixerProtocolPresets.ts, server/constants/mixerProtocols/StuderOnAirEmber.ts, server/constants/mixerProtocols/StuderVistaEmber.ts, server/utils/MixerConnection.ts, server/utils/mixerConnections/StuderOnAirMixerConnection.ts
Hacked support for old Studer Ember protocol
=> Basic On-Air 3000 support

README.md, package.json, server/constants/mixerProtocols/StuderVistaEmber.ts, server/utils/MixerConnection.ts, server/utils/mixerConnections/StuderVistaMixerConnection.ts
Initial support for Vista 1-5-9
Mono, Stereo, 51 - Fadercontrol.
Only FROM Sisyfos TO mixer
no 2-way connection.
=> Vista 1-5-9 support

server/constants/mixerProtocols/StuderVistaEmber.ts, server/utils/mixerConnections/StuderVistaMixerConnection.ts
Aux 2-way support
Code cleanup in Vista Ember
=> Feat/2way vista Aux 2-way response

server/reducers/channelsReducer.ts, server/utils/mixerConnections/StuderVistaMixerConnection.ts
A bug that only affected mixer protocols with multiple channelstypes (Studer Vista)
=> fix: update all channels in channelReducers->SET_COMPLETE_CH_STATE

Docs/CasparCG-Example/sisyfos-casparcg-geometry.json, server/constants/MixerProtocolInterface.ts, server/constants/mixerProtocols/casparCGMaster.ts, server/utils/mixerConnections/CasparCGConnection.ts
Also refactors the monitor/PFL property in the geometry file
=> feat(casparcg): adds CasparCG monitoring support for NEXT/PST

CHANGELOG.md, package.json, server/MainThreadHandler.ts, server/utils/MixerConnection.ts, server/utils/mixerConnections/OscMixerConnection.ts, yarn.lock
Merged version of NRKNO vmix support PR. It was delayed because of an vulnerability in vmix-js-utils, now fixed.
https://github.com/tv2/sisyfos-audio-controller/pull/181
=> Nrkno feat/vmix

client/assets/css/Channel.css, client/components/Channel.tsx
Feat: Double clicking will set the Fader to 0dB
=> feat: Double click on Fader in the 0dB area will set the Fader to 0dB

client/assets/css/MicTally.css, client/components/MicTally.tsx
Still needs some verification on how to display faders (VO vs PGM vs mute) and when they should be controllable (e.g. manual vs automatic).
=> Feat/sof 682/mic tally fader toggling

package.json, server/MainThreadHandler.ts, server/expressHandler.ts, server/reducers/fadersReducer.ts, server/utils/AutomationConnection.ts, server/utils/MixerConnection.ts, server/utils/SettingsStorage.ts, server/utils/SnapshotHandler.ts, server/utils/logger.ts, server/utils/migrations.ts, server/utils/mixerConnections/CasparCGConnection.ts, server/utils/mixerConnections/EmberMixerConnection.ts, server/utils/mixerConnections/LawoRubyConnection.ts, server/utils/mixerConnections/MidiMixerConnection.ts, server/utils/mixerConnections/OscMixerConnection.ts, server/utils/mixerConnections/SSLMixerConnection.ts, server/utils/mixerConnections/StuderMixerConnection.ts, server/utils/mixerConnections/StuderVistaMixerConnection.ts, server/utils/mixerConnections/VMixMixerConnection.ts, server/utils/mixerConnections/YamahaQlClConnection.ts, server/utils/remoteConnections/HuiMidiRemoteConnection.ts, server/utils/remoteConnections/SkaarhojRemoteConnection.ts, yarn.lock
Hi Kasper and Balte, we have decided to improve and simplify the logging in Sisyfos. This means that we have chosen to move away from https://www.npmjs.com/package/winston to a tv2media specific which dosen't include any other dependencies https://www.npmjs.com/package/@tv2media/logger.  We have removed all console logs and we are new using 5 log formats, error, warn, info, debug, trace. Futher details about the tv2media logging framework can be read in the project README. 
A big reason for this is to be able to log JSON and hereby make the logs more searchable in log management software e.g. ElasticSearch, Kibana).
=> feat: Changed logger from winston to tv2 mediatech logger.

client/index.ejs
=> Develop since 4.15.0

Dockerfile
Update Dockerbuild to 16-alphine to match Git action tests
=> Develop since v4.15.1

server/reducers/fadersReducer.ts, server/utils/remoteConnections/SkaarhojRemoteConnection.ts
Parsing old faders settings to new setup is now working
=> fix: When chaning number of faders, all monitor settings and routing was lost.

.gitignore, server/src/utils/MixerConnection.ts, shared/src/constants/MixerProtocolInterface.ts, shared/src/constants/mixerProtocols/DmxIs.ts, shared/src/constants/mixerProtocols/LawoMC2.ts, shared/src/constants/mixerProtocols/LawoRelayVrx4.ts, shared/src/constants/mixerProtocols/LawoRuby.ts, shared/src/constants/mixerProtocols/SSLsystemT.ts, shared/src/constants/mixerProtocols/StuderOnAirEmber.ts, shared/src/constants/mixerProtocols/StuderVistaEmber.ts, shared/src/constants/mixerProtocols/ardourMaster.ts, shared/src/constants/mixerProtocols/behringerXrMaster.ts, shared/src/constants/mixerProtocols/casparCGMaster.ts, shared/src/constants/mixerProtocols/genericMidi.ts, shared/src/constants/mixerProtocols/midasMaster.ts, shared/src/constants/mixerProtocols/reaperMaster.ts, shared/src/constants/mixerProtocols/vMix.ts, shared/src/constants/mixerProtocols/yamahaQLCL.ts
Refactor fade up/down to be based on time passed instead of how many "steps" have been run
=> SOF-937 Refactor fade up and down to use time based fading

README.md, server/src/utils/mixerConnections/SSLMixerConnection.ts
=> feat: SSL code update and cleanup

server/src/utils/mixerConnections/LawoRubyConnection.ts
We had some issues using sisyfos with the lawo powercore where sisyfos would crash intermittently. We believe this PR fixes any issues we were having.
=> chore: add some extra guards for promises in ruby protocol

shared/src/reducers/fadersReducer.ts
fix: when removing assignment on fader it didn't take mixerIndex into account
=> fix: removing assignment on fader

client/src/assets/css/NoUiSlider.css
Small fix, as noUiSlide now uses css noUiorig height correctly. So changed the Heigth.
=> fix: latest version of noUiSclider are using css ".noUi-origin

server/package.json, server/src/utils/mixerConnections/EmberMixerConnection.ts, server/src/utils/mixerConnections/LawoRubyConnection.ts, yarn.lock
This PR contains 2 small bug fixes for the Lawo Ruby integration. It also updates the emberplus-connection library.
This PR is opened on behalf of NRK.
=> Fix: ruby subscriptions

client/src/components/ChannelRouteSettings.tsx, server/src/MainThreadHandler.ts, server/src/utils/SettingsStorage.ts, server/src/utils/migrations.ts, server/src/utils/mixerConnections/CasparCGConnection.ts, server/src/utils/mixerConnections/EmberMixerConnection.ts, server/src/utils/mixerConnections/LawoRubyConnection.ts, server/src/utils/mixerConnections/OscMixerConnection.ts, server/src/utils/mixerConnections/VMixMixerConnection.ts, shared/src/reducers/channelsReducer.ts, shared/src/reducers/fadersReducer.ts
=> Merge 'Fix/sisyfos init procedure' into 'feat/refactor-typesafety'

server/src/utils/MixerConnection.ts
Using Automation protocol: TSR Sending faderLevel with a fadetime and immediately after send a PGM OFF
Sisyfos would start fading to the new faderlevel (next targetLevel), and when told to fadedown while it still was fading, it would start a new fade from the targetLevel even though Sisyfos only was half way to that fade.
And this could give some serious volume bumps, if user manually had adjusted the level.
Added a  currentOutputLevel[] that are used if fadeActive is true
As a side note, the function fadeDown() has also been moved up so it's just after fadeUp() in the MixergenericConnection class. Not a functional change, but it makes more sense when looking at the code.
=> fix: setting PGM ON/OFF while faderLevel is fading caused level bump
