src/utils/DEFAULTS.js, src/utils/OscServer.js, src/utils/productSpecific/behringer.js
Ping command was only initiated once (due to using a ref to a func instead of a func)
Behringer Meter, works but still uncalibrated
=> Behringer Meter, works but still uncalibrated

package.json
yarn package-release will build for linux, Mac and windows when run on a Mac
=> Webpack: yarn package-release Mac-win-linux on mac

src/constants/AutomationPresets.ts, src/utils/AutomationConnection.ts
This PR adds the functionality to let an automation system ping sisyfos, to verify connectivity status.
An OSC-command "/ping/1234" will make sisyfos return "/pong" with the same value "1234".
=> OSC ping feature

client/assets/css/App.css
This PR adds `overscroll-behavior: contain;` to the body tag, to prevent the behavior where when user scrolls the iframe contents and reaches the end, the browser will start scrolling the outer page.
=> fix: Prevent scrolling of parent when in an iframe

client/index.tsx, client/utils/SocketClientHandlers.ts, server/utils/vuServer.ts
This PR adds a subscription request every time the client reconnects to the server. This fixes stuck metering after reconnection.
=> fix: subscribe to VU meters upon connection

client/assets/css/Channel.css, client/assets/css/NoUiSlider.css, client/components/Channel.tsx, client/components/Channels.tsx, client/utils/SocketClientHandlers.ts, server/constants/MixerProtocolInterface.ts, server/constants/mixerProtocols/LawoMC2.ts, server/constants/mixerProtocols/LawoRuby.ts, server/reducers/settingsActions.ts, server/reducers/settingsReducer.ts, server/utils/dbConversion.ts, server/utils/mixerConnections/EmberMixerConnection.ts, server/utils/mixerConnections/LawoRubyConnection.ts, server/utils/mixerConnections/OscMixerConnection.ts, server/utils/mixerConnections/SSLMixerConnection.ts, server/utils/mixerConnections/StuderVistaMixerConnection.ts, server/utils/mixerConnections/YamahaQlClConnection.ts
This PR contains various features and fixes we did while deploying a gallery for NRK.
- feat: show dB labels next to the fader if the mixer protocol supports it
- feat: ember+ snapshots from the mixer
- fix: mc2 gets boolean from ember+, not numbers
- fix: layout when there's less faders than screen width
- changed the mc2 input gain parameter
- fix: mixer status (was not updated before)
- fix: show storage button when settings are disabled
- change the color of the PFL button to green
=> Various fixes and features

client/utils/SocketClientHandlers.ts, server/MainThreadHandler.ts, server/reducers/fadersReducer.ts, server/utils/AutomationConnection.ts, server/utils/mixerConnections/CasparCGConnection.ts, server/utils/mixerConnections/EmberMixerConnection.ts, server/utils/mixerConnections/LawoRubyConnection.ts, server/utils/mixerConnections/OscMixerConnection.ts, server/utils/mixerConnections/StuderVistaMixerConnection.ts
Contains the following fixes from the NRK fork:
* Mixer online status
* UI crash when an invalid channel number was used by automation
* hide-unused-lawo-ruby-channels
=> Misc. fixes

client/assets/css/LabelSettings.css, client/components/App.tsx, client/components/ChanStrip.tsx, client/components/ChanStripFull.tsx, client/components/Channel.tsx, client/components/ChannelMonitorOptions.tsx, client/components/ChannelRouteSettings.tsx, client/components/Channels.tsx, client/components/Labels.tsx, client/components/MiniChanStrip.tsx, client/components/MiniChannel.tsx, client/components/PagesSettings.tsx, client/components/Settings.tsx, client/utils/labels.ts, server/MainThreadHandler.ts, server/constants/SOCKET_IO_DISPATCHERS.ts, server/reducers/channelActions.ts, server/reducers/channelsReducer.ts, server/reducers/faderActions.ts, server/reducers/fadersReducer.ts, server/reducers/settingsActions.ts, server/reducers/settingsReducer.ts, server/utils/AutomationConnection.ts, server/utils/mixerConnections/CasparCGConnection.ts, server/utils/mixerConnections/EmberMixerConnection.ts, server/utils/mixerConnections/LawoRubyConnection.ts, server/utils/mixerConnections/OscMixerConnection.ts, server/utils/mixerConnections/StuderMixerConnection.ts
This PR adds a labeling system, labels can either come from automation, the channel names on the mixer or set by the user. The user can choose which types of labels are used or leave it to automatic where Sisyfos shall use the user defined, automation or channel label.
Additionally external labels can be flushed from the system if required / convenient.
The automation connection has been refactored to reduce code repetition as well as allow the use of labels instead of channel numbers.
=> Feature: label system

server/utils/AutomationConnection.ts, server/utils/labels.ts
When requesting a full state, Sisyfos will include the label currently shown to the user
=> Feat: emit labels over automation connection

server/utils/mixerConnections/productSpecific/midas.ts
Midas Metering did not show logaritmic (dB)
=> fix: Midas metering convert dB to Lin

server/constants/mixerProtocols/midasMaster.ts, server/utils/mixerConnections/OscMixerConnection.ts
Fix: when loading a preset, new Midas values was not received 
Fix: mixLabel maxLabel should not be used for OSC conversion. Use min and max instead.
=> fix: Midas - when loading a new preset, settings was not received

.github/version, .github/workflows/node-ci.prod.yml
Previous behaviour was that the docker hub tags were using the old version, which was read from package.json.
To counter this, the version gained from bumping the version is used instead.
=> fix: Use version from bump-version instead of package.json in node-ci.prod

.github/version, .github/workflows/node-ci.prod.yml
Updated changelog and package.json should now be included in build.
The issue was that the job that builds and pushes were referring to the branch at the commit which triggered the workflow.
Thus the ref of these jobs has been updated to use the commit SHA of the commit created in the workflow for the package.json and the CHANGELOG.md.
=> fix: Bumped github actions workflows.

client/components/Settings.tsx, server/MainThreadHandler.ts, server/utils/mixerConnections/OscMixerConnection.ts
The save button in Settings are now changed to "SAVE & RESTART" and a popup alert ensure that the client knows Sisyfos is restarting. (And delays the reload so it's not reloading before the new config are used on the server)
=> Feat/better config update handling - (now into develop)

server/MainThreadHandler.ts
The assigned channels are recalculated every time the automation system sends an update. This is unnecessary and since the recalculation is costly can hamper performance greatly. The calculation should only be done when a channel is reassigned to a different fader.
=> fix: remove recalcAssignedChannels from hot path

client/src/assets/css/MicTally.css
By doing so, the component can fit in smaller areas like the Kommentator View in Sofie QBox.
=> SIS-37/Removed min-height for mic-tally.

server/src/utils/mixerConnections/SSLMixerConnection.ts, server/src/utils/mixerConnections/StuderMixerConnection.ts, server/src/utils/mixerConnections/StuderVistaMixerConnection.ts, server/src/utils/mixerConnections/YamahaQlClConnection.ts
Changed `new Buffer(` to `Buffer.from(`.
=> Sis 36/new buffer deprecated

server/src/utils/AutomationConnection.ts, server/src/utils/mixerConnections/VMixMixerConnection.ts
- Changed AutomationConnection.setupAutomationConnection() to use debug level log instead of info level.
- Included message as data as part of log instead of only a snippet of the log, which was undefined
- Changed VMixMixerConnection.checkFxCommands to match how OscMixerConnection.checkFxCommands does the same log (i.e uncommented log statement)
=> fix(SOF-875): Lowered log level of a log call, reducing logs significantly.

server/src/utils/mixerConnections/VMixMixerConnection.ts
This PR is being opened on behalf of [TV 2 Norge](https://github.com/tv2norge).
Closes #255 
This is a naive solution from someone who is new to Sisyfos. It is possible that this has repercussions and consequences that I am not aware of. But, it does get Sisyfos to at least run for me.
=> fix(vmix): don't crash when vmix has more audio channels than sisyfos is configured to handle

server/src/MainThreadHandler.ts, server/src/utils/SettingsStorage.ts, server/src/utils/SnapshotHandler.ts
fix: location of storage folder was not the same when save and recalling snapshot, on mac and PC
One const is now the base for all folderreferences.
=> fix: location of storage folder was not the same when save and recall

server/src/utils/mixerConnections/VMixMixerConnection.ts
VMix API can be _quite_ slow hence we need to be really careful with the amount of commands we send to it. This PR mostly reduces the number of commands during a fade. This makes controlling vmix somewhat more reliable.
In addition, it allows some time between muting and pulling up a fader, as that command can be particularly slow to take effect.
=> Fix: vmix blips

README.md, server/src/utils/AutomationConnection.ts, server/src/utils/MixerConnection.ts
To allow fade times to be adjusted with each level change this PR adds an additional (optional) `fadeTime` argument to the `/ch/1/mix/faderlevel` command.
Additionally this PR prevents fades from occurring if the start and end levels are the same.
=> Allow fade times to be set with each level change

README.md, client/index.tsx, server/src/expressHandler.ts
Quick PR to add a `ROOT_PATH` environment variable to serve the client on a different path.
Aimed at use behind reverse proxies such as Traefik or nginx, E.G. `ROOT_PATH=/sisyfos`
=> Configurable root path for serving the client

client/src/components/ChannelRouteSettings.tsx, server/src/MainThreadHandler.ts, server/src/utils/SettingsStorage.ts, server/src/utils/migrations.ts, server/src/utils/mixerConnections/CasparCGConnection.ts, server/src/utils/mixerConnections/EmberMixerConnection.ts, server/src/utils/mixerConnections/LawoRubyConnection.ts, server/src/utils/mixerConnections/OscMixerConnection.ts, server/src/utils/mixerConnections/VMixMixerConnection.ts, shared/src/reducers/channelsReducer.ts, shared/src/reducers/fadersReducer.ts
Hi, I've found and fixed some issues that I've found when starting up Sisyfos for the very first time (i.e. no saved files):
- On MacOS the storage path was inconsistent, causing the default snapshot to be saved in a different place than it was opened from.
- Some robustness about dispatching updates to the channels, now it checks if the mixerIndex and channelIndex are actually valid for the store.
- I've changed some code so that all channels are initialised immediately upon first start and all the faders are routed 1:1. Makes it a bit easier to restore from just a settings file.
Just for transparency: these changes are contributed by SuperFly.tv on behalf of BBC. (Just putting this here as I usually contribute on behalf of NRK)
=> Fix some small issues around first startup

server/src/expressHandler.ts, server/src/utils/MixerConnection.ts, server/src/utils/outputLevelServer.ts, server/src/utils/vuServer.ts
Adds an additional subscription option for the Socket.IO connection to get the output level of the mixer.
Intended for use with remote fader panel applications where real-time updates of the levels are required.
Now pointing at develop
=> Mixer output level subscription

.github/dependabot.yml
To have a flow where changes starts at develop and is tested prior to being pushed to the default branch, Dependabot should target the `develop` branch instead of master.
=> SOF-1802: Configure Dependabot to look for updates in Yarn and GitHub Actions weekly and target 'develop' instead of 'master'.

server/src/utils/AutomationConnection.ts
Automation protocol - setchannel did not update mixerConnection, and if another setChannel was called while the channel was in a fade, the channels state would conflict, and jump to previous vol level.
=> fix: set-channel didn't update mixerconnection 

README.md, server/src/utils/MixerConnection.ts
This contribution is on behalf of BBC.
Issue:
If faderlevel was set in UI while a long fade was active, the audio would jump to new UI level and then back and continue the fade.
Solution:
When setting faderLevel with fadeTime to 0, a jumpToLevel() has been added. This ensures that running timers are cleared and avoid the resources/time a fade timer takes to start.
=> bug fix - change UI level while fadeactive
